name: CI

on:
  push:	
    branches:	
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ">=13"
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
